In [ ]:
import pandas as pd

df = pd.read_csv("social_media.csv")
df
import pandas as pd
import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

def clean_social_media(df):

    # --- Handle Missing Values ---
    df['likes'] = df['likes'].fillna(0)
    df['shares'] = df['shares'].fillna(0)

    # --- Cleaning Text ---
    def clean_text(text):
        if pd.isna(text):
            return ""
        text = text.lower()
        text = re.sub(r'<.*?>', '', text)        # remove html
        text = re.sub(r'[^a-z\s]', '', text)     # remove punctuation/symbols
        words = [w for w in text.split() if w not in ENGLISH_STOP_WORDS]
        return " ".join(words)

    df['clean_text'] = df['post_text'].apply(clean_text)

    # --- Timestamp Features ---
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['hour'] = df['timestamp'].dt.hour
    df['weekday'] = df['timestamp'].dt.day_name()

    # --- Remove Duplicate Posts ---
    df = df.drop_duplicates(subset='clean_text')

    return df

cleaned_df = clean_social_media(df)
cleaned_df

,post_id,user,post_text,likes,shares,timestamp,clean_text,hour,weekday
0,1,user_1,This is a sample POST!!! #fun,20.0,1.0,2025-01-01 00:00:00,sample post fun,0,Wednesday
1,2,user_2,<html>Great Day!</html>,20.0,3.0,2025-01-01 06:00:00,great day,6,Wednesday

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving social_media.csv to social_media (1).csv

In [ ]:
import pandas as pd
df = pd.read_csv(list(uploaded.keys())[0])  # auto detect file name
df.head()

,post_id,user,post_text,likes,shares,timestamp
0,1,user_1,This is a sample POST!!! #fun,20.0,1.0,2025-01-01 00:00:00
1,2,user_2,<html>Great Day!</html>,20.0,3.0,2025-01-01 06:00:00
2,3,user_3,This is a sample POST!!! #fun,20.0,1.0,2025-01-01 12:00:00
3,4,user_4,<html>Great Day!</html>,100.0,NaN,2025-01-01 18:00:00
4,5,user_5,This is a sample POST!!! #fun,20.0,5.0,2025-01-02 00:00:00

In [ ]:
import pandas as pd
import re
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

In [ ]:
def clean_social_media(df):

    # --- Handle Missing Values ---
    df['likes'] = df['likes'].fillna(0)
    df['shares'] = df['shares'].fillna(0)

    # --- Cleaning Text ---
    def clean_text(text):
        if pd.isna(text):
            return ""

        text = text.lower()
        text = re.sub(r'<.*?>', '', text)  # remove html
        text = re.sub(r'[^a-z\s]', '', text)  # remove punctuation/symbols

        words = [w for w in text.split() if w not in ENGLISH_STOP_WORDS]
        return " ".join(words)

    df['clean_text'] = df['post_text'].apply(clean_text)

    # --- Convert Timestamp ---
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['hour'] = df['timestamp'].dt.hour
    df['weekday'] = df['timestamp'].dt.day_name()

    # --- Remove duplicates ---
    df = df.drop_duplicates(subset=['post_text'])

    return df

In [ ]:
cleaned_df = clean_social_media(df)
cleaned_df.head()

,post_id,user,post_text,likes,shares,timestamp,clean_text,hour,weekday
0,1,user_1,This is a sample POST!!! #fun,20.0,1.0,2025-01-01 00:00:00,sample post fun,0,Wednesday
1,2,user_2,<html>Great Day!</html>,20.0,3.0,2025-01-01 06:00:00,great day,6,Wednesday

In [ ]:
# ---- TEST CASES ----

# Test 1: Check if missing likes are filled with 0
test1 = cleaned_df['likes'].isna().sum() == 0
print("Test 1 - Missing likes handled:", test1)

# Test 2: Check if clean_text column exists
test2 = 'clean_text' in cleaned_df.columns
print("Test 2 - clean_text column created:", test2)

# Test 3: Check if timestamp converted properly
test3 = pd.api.types.is_datetime64_any_dtype(cleaned_df['timestamp'])
print("Test 3 - Timestamp converted:", test3)

# Test 4: Check duplicates removed
test4 = cleaned_df.duplicated(subset=['post_text']).sum() == 0
print("Test 4 - Duplicates removed:", test4)

# Test 5: Check if hour and weekday columns are created
test5 = 'hour' in cleaned_df.columns and 'weekday' in cleaned_df.columns
print("Test 5 - Hour & Weekday columns created:", test5)

Test 1 - Missing likes handled: True
Test 2 - clean_text column created: True
Test 3 - Timestamp converted: True
Test 4 - Duplicates removed: True
Test 5 - Hour & Weekday columns created: True

In [ ]:
# --- CLEANING STEPS ---

cleaned_df = df.copy()

# 1. Remove HTML tags
import re
cleaned_df['clean_post'] = cleaned_df['post_text'].apply(lambda x: re.sub('<.*?>', '', str(x)))

# 2. Fill missing likes/shares with 0
cleaned_df['likes'] = cleaned_df['likes'].fillna(0)
cleaned_df['shares'] = cleaned_df['shares'].fillna(0)

# 3. Convert timestamp to datetime
cleaned_df['timestamp'] = pd.to_datetime(cleaned_df['timestamp'])

# 4. Extract hour + weekday
cleaned_df['hour'] = cleaned_df['timestamp'].dt.hour
cleaned_df['weekday'] = cleaned_df['timestamp'].dt.day_name()

# 5. Remove duplicate posts
cleaned_df = cleaned_df.drop_duplicates(subset=['clean_post'])

In [ ]:
print("================ TASK 1: SOCIAL MEDIA CLEANING ==================\n")

# --- BEFORE CLEANING ---
print("--- BEFORE CLEANING ---")
print(df[['post_id', 'user', 'post_text', 'likes', 'shares', 'timestamp']])
print("\n")

# --- AFTER CLEANING ---
print("--- AFTER CLEANING ---")
print(cleaned_df[['post_id', 'user', 'post_text', 'likes', 'shares', 'timestamp', 'clean_post', 'hour', 'weekday']])
print("\n")

# ================= TEST CASES =================
tests_passed = True

# Test 1: Missing likes handled
if cleaned_df['likes'].isna().sum() == 0:
    pass
else:
    tests_passed = False

# Test 2: clean_post column exists
if 'clean_post' in cleaned_df.columns:
    pass
else:
    tests_passed = False

# Test 3: timestamp is datetime
if pd.api.types.is_datetime64_any_dtype(cleaned_df['timestamp']):
    pass
else:
    tests_passed = False

# Test 4: duplicates removed
if cleaned_df.duplicated(subset=['clean_post']).sum() == 0:
    pass
else:
    tests_passed = False

# Test 5: hour + weekday exist
if 'hour' in cleaned_df.columns and 'weekday' in cleaned_df.columns:
    pass
else:
    tests_passed = False

# Final Output
if tests_passed:
    print("Task 1 Passed All Tests ✔")
else:
    print("❌ Some Tests Failed. Fix Required.")

================ TASK 1: SOCIAL MEDIA CLEANING ==================

--- BEFORE CLEANING ---
    post_id     user                      post_text  likes  shares  \
0         1   user_1  This is a sample POST!!! #fun   20.0     1.0
1         2   user_2        <html>Great Day!</html>   20.0     3.0
2         3   user_3  This is a sample POST!!! #fun   20.0     1.0
3         4   user_4        <html>Great Day!</html>  100.0     0.0
4         5   user_5  This is a sample POST!!! #fun   20.0     5.0
5         6   user_6        <html>Great Day!</html>    5.0     1.0
6         7   user_7  This is a sample POST!!! #fun   20.0     5.0
7         8   user_8        <html>Great Day!</html>   10.0     5.0
8         9   user_9  This is a sample POST!!! #fun    5.0     5.0
9        10  user_10        <html>Great Day!</html>    5.0     5.0
10       11  user_11  This is a sample POST!!! #fun    0.0     1.0
11       12  user_12        <html>Great Day!</html>   10.0     3.0
12       13  user_13  This is a sample POST!!! #fun    5.0     5.0
13       14  user_14        <html>Great Day!</html>    5.0     1.0
14       15  user_15  This is a sample POST!!! #fun    0.0     5.0
15       16  user_16        <html>Great Day!</html>    0.0     1.0
16       17  user_17  This is a sample POST!!! #fun    0.0     3.0
17       18  user_18        <html>Great Day!</html>   20.0     3.0
18       19  user_19  This is a sample POST!!! #fun   10.0     0.0
19       20  user_20        <html>Great Day!</html>    0.0     0.0

             timestamp
0  2025-01-01 00:00:00
1  2025-01-01 06:00:00
2  2025-01-01 12:00:00
3  2025-01-01 18:00:00
4  2025-01-02 00:00:00
5  2025-01-02 06:00:00
6  2025-01-02 12:00:00
7  2025-01-02 18:00:00
8  2025-01-03 00:00:00
9  2025-01-03 06:00:00
10 2025-01-03 12:00:00
11 2025-01-03 18:00:00
12 2025-01-04 00:00:00
13 2025-01-04 06:00:00
14 2025-01-04 12:00:00
15 2025-01-04 18:00:00
16 2025-01-05 00:00:00
17 2025-01-05 06:00:00
18 2025-01-05 12:00:00
19 2025-01-05 18:00:00


--- AFTER CLEANING ---
   post_id    user                      post_text  likes  shares  \
0        1  user_1  This is a sample POST!!! #fun   20.0     1.0
1        2  user_2        <html>Great Day!</html>   20.0     3.0

            timestamp                     clean_post  hour    weekday
0 2025-01-01 00:00:00  This is a sample POST!!! #fun     0  Wednesday
1 2025-01-01 06:00:00                     Great Day!     6  Wednesday


Task 1 Passed All Tests ✔

In [27]:
from google.colab import files
uploaded = files.upload()

Saving financial_data.csv to financial_data (1).csv

In [28]:
import pandas as pd
df = pd.read_csv(list(uploaded.keys())[0])  # auto detect file name
df.head()

         date  closing_price  volume
0  2025-01-01            NaN  5000.0
1  2025-01-02         131.04  2000.0
2  2025-01-03         138.26  2000.0
3  2025-01-04         164.68     NaN
4  2025-01-05         165.06  5000.0

In [29]:
import pandas as pd
import numpy as np

print("================ TASK 2: STOCK PRICE CLEANING ==================\n")

# =========================================================
# 1️⃣ LOAD DATA (from uploaded file)
# =========================================================

df = pd.read_csv(list(uploaded.keys())[0])   # auto-read uploaded CSV

# =========================================================
# 2️⃣ BEFORE CLEANING
# =========================================================

print("--- BEFORE CLEANING ---")
print(df)
print("\n")


# =========================================================
# 3️⃣ CLEANING LOGIC
# =========================================================

cleaned_df = df.copy()

# Convert date column to datetime
cleaned_df['date'] = pd.to_datetime(cleaned_df['date'])

# Fill missing closing_price using forward-fill then backward-fill
cleaned_df['closing_price'] = cleaned_df['closing_price'].astype(float)
cleaned_df['closing_price'] = cleaned_df['closing_price'].ffill().bfill()

# Fill missing volume with the mean volume
cleaned_df['volume'] = cleaned_df['volume'].astype(float)
cleaned_df['volume'] = cleaned_df['volume'].fillna(cleaned_df['volume'].mean())

# Add a new column: daily_price_change
cleaned_df['daily_price_change'] = cleaned_df['closing_price'].diff().fillna(0)


# =========================================================
# 4️⃣ AFTER CLEANING
# =========================================================

print("--- AFTER CLEANING ---")
print(cleaned_df)
print("\n")


# =========================================================
# 5️⃣ TEST CASES
# =========================================================

tests_passed = True

# TEST 1 — No missing values
if cleaned_df.isna().sum().sum() == 0:
    pass
else:
    tests_passed = False

# TEST 2 — closing_price is fully filled
if cleaned_df['closing_price'].isna().sum() == 0:
    pass
else:
    tests_passed = False

# TEST 3 — volume is fully filled
if cleaned_df['volume'].isna().sum() == 0:
    pass
else:
    tests_passed = False

# TEST 4 — daily_price_change column exists
if "daily_price_change" in cleaned_df.columns:
    pass
else:
    tests_passed = False


# =========================================================
# 6️⃣ FINAL RESULT
# =========================================================

if tests_passed:
    print("Task 2 Passed All Tests ✔")
else:
    print("❌ Some Tests Failed. Fix Required.")

================ TASK 2: STOCK PRICE CLEANING ==================

--- BEFORE CLEANING ---
          date  closing_price  volume
0   2025-01-01            NaN  5000.0
1   2025-01-02         131.04  2000.0
2   2025-01-03         138.26  2000.0
3   2025-01-04         164.68     NaN
4   2025-01-05         165.06  5000.0
5   2025-01-06         137.99  1500.0
6   2025-01-07         151.00  5000.0
7   2025-01-08            NaN  1500.0
8   2025-01-09         190.09  1500.0
9   2025-01-10         135.16  1000.0
10  2025-01-11         146.99  5000.0
11  2025-01-12         120.55  2000.0
12  2025-01-13         168.97     NaN
13  2025-01-14         149.75  1500.0
14  2025-01-15            NaN  1000.0
15  2025-01-16         180.33  5000.0
16  2025-01-17         162.83  1000.0
17  2025-01-18         147.76  1500.0
18  2025-01-19         164.34  5000.0
19  2025-01-20         122.91     NaN
20  2025-01-21         101.11  2000.0
21  2025-01-22            NaN     NaN
22  2025-01-23         156.71  1000.0
23  2025-01-24         191.67  1000.0
24  2025-01-25         167.01  2000.0
25  2025-01-26         193.82  1500.0
26  2025-01-27         116.65  2000.0
27  2025-01-28         145.41  2000.0
28  2025-01-29            NaN  2000.0
29  2025-01-30         123.02  1500.0


--- AFTER CLEANING ---
         date  closing_price       volume  daily_price_change
0  2025-01-01         131.04  5000.000000                0.00
1  2025-01-02         131.04  2000.000000                0.00
2  2025-01-03         138.26  2000.000000                7.22
3  2025-01-04         164.68  2365.384615               26.42
4  2025-01-05         165.06  5000.000000                0.38
5  2025-01-06         137.99  1500.000000              -27.07
6  2025-01-07         151.00  5000.000000               13.01
7  2025-01-08         151.00  1500.000000                0.00
8  2025-01-09         190.09  1500.000000               39.09
9  2025-01-10         135.16  1000.000000              -54.93
10 2025-01-11         146.99  5000.000000               11.83
11 2025-01-12         120.55  2000.000000              -26.44
12 2025-01-13         168.97  2365.384615               48.42
13 2025-01-14         149.75  1500.000000              -19.22
14 2025-01-15         149.75  1000.000000                0.00
15 2025-01-16         180.33  5000.000000               30.58
16 2025-01-17         162.83  1000.000000              -17.50
17 2025-01-18         147.76  1500.000000              -15.07
18 2025-01-19         164.34  5000.000000               16.58
19 2025-01-20         122.91  2365.384615              -41.43
20 2025-01-21         101.11  2000.000000              -21.80
21 2025-01-22         101.11  2365.384615                0.00
22 2025-01-23         156.71  1000.000000               55.60
23 2025-01-24         191.67  1000.000000               34.96
24 2025-01-25         167.01  2000.000000              -24.66
25 2025-01-26         193.82  1500.000000               26.81
26 2025-01-27         116.65  2000.000000              -77.17
27 2025-01-28         145.41  2000.000000               28.76
28 2025-01-29         145.41  2000.000000                0.00
29 2025-01-30         123.02  1500.000000              -22.39


Task 2 Passed All Tests ✔

In [30]:
from google.colab import files
uploaded = files.upload()

Saving iot_sensor.csv to iot_sensor (1).csv

In [31]:
import pandas as pd
df = pd.read_csv(list(uploaded.keys())[0])  # auto detect file name
df.head()

             timestamp sensor_id  temperature  humidity
0  2025-02-01 00:00:00        S2         24.0      40.0
1  2025-02-01 01:00:00        S3         30.0       NaN
2  2025-02-01 02:00:00        S1         24.0      50.0
3  2025-02-01 03:00:00        S2         24.0       NaN
4  2025-02-01 04:00:00        S3         23.0      42.0

In [32]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder

print("================ TASK 3: IoT SENSOR DATA PREPROCESSING ==================\n")

# =========================================================
# 1️⃣ LOAD DATA
# =========================================================
df = pd.read_csv(list(uploaded.keys())[0])

# =========================================================
# 2️⃣ BEFORE CLEANING
# =========================================================
print("--- BEFORE CLEANING ---")
print(df)
print("\n")


# =========================================================
# 3️⃣ CLEANING & PREPROCESSING
# =========================================================

cleaned_df = df.copy()

# Convert timestamp to datetime
cleaned_df['timestamp'] = pd.to_datetime(cleaned_df['timestamp'])

# Handle missing values — forward fill
cleaned_df[['temperature', 'humidity']] = cleaned_df[['temperature', 'humidity']].ffill()

# Remove sensor drift using rolling mean (window = 3)
cleaned_df['temperature_smoothed'] = cleaned_df['temperature'].rolling(window=3, min_periods=1).mean()
cleaned_df['humidity_smoothed'] = cleaned_df['humidity'].rolling(window=3, min_periods=1).mean()

# Normalize using Standard Scaler
scaler = StandardScaler()
cleaned_df[['temp_norm', 'hum_norm']] = scaler.fit_transform(
    cleaned_df[['temperature_smoothed', 'humidity_smoothed']]
)

# Encode sensor IDs
encoder = LabelEncoder()
cleaned_df['sensor_id_encoded'] = encoder.fit_transform(cleaned_df['sensor_id'])


# =========================================================
# 4️⃣ AFTER CLEANING
# =========================================================
print("--- AFTER CLEANING ---")
print(cleaned_df)
print("\n")


# =========================================================
# 5️⃣ TEST CASES
# =========================================================

tests_passed = True

# TEST 1 — No missing values in temperature & humidity
if cleaned_df[['temperature', 'humidity']].isna().sum().sum() == 0:
    pass
else:
    tests_passed = False

# TEST 2 — Normalized columns exist
if "temp_norm" in cleaned_df.columns and "hum_norm" in cleaned_df.columns:
    pass
else:
    tests_passed = False

# TEST 3 — Encoded sensor_id column exists
if "sensor_id_encoded" in cleaned_df.columns:
    pass
else:
    tests_passed = False

# TEST 4 — Rolling mean columns exist
if "temperature_smoothed" in cleaned_df.columns and "humidity_smoothed" in cleaned_df.columns:
    pass
else:
    tests_passed = False


# =========================================================
# 6️⃣ FINAL RESULT
# =========================================================

if tests_passed:
    print("Task 3 Passed All Tests ✔")
else:
    print("❌ Some Tests Failed. Fix Required.")

================ TASK 3: IoT SENSOR DATA PREPROCESSING ==================

--- BEFORE CLEANING ---
              timestamp sensor_id  temperature  humidity
0   2025-02-01 00:00:00        S2         24.0      40.0
1   2025-02-01 01:00:00        S3         30.0       NaN
2   2025-02-01 02:00:00        S1         24.0      50.0
3   2025-02-01 03:00:00        S2         24.0       NaN
4   2025-02-01 04:00:00        S3         23.0      42.0
5   2025-02-01 05:00:00        S3          NaN      40.0
6   2025-02-01 06:00:00        S2         24.0      45.0
7   2025-02-01 07:00:00        S3          NaN      45.0
8   2025-02-01 08:00:00        S1         24.0       NaN
9   2025-02-01 09:00:00        S2         22.0       NaN
10  2025-02-01 10:00:00        S1          NaN      50.0
11  2025-02-01 11:00:00        S2         23.0       NaN
12  2025-02-01 12:00:00        S3         23.0      42.0
13  2025-02-01 13:00:00        S1         22.0      45.0
14  2025-02-01 14:00:00        S1         24.0      42.0
15  2025-02-01 15:00:00        S1         23.0      50.0
16  2025-02-01 16:00:00        S2         30.0      50.0
17  2025-02-01 17:00:00        S2         22.0      50.0
18  2025-02-01 18:00:00        S3          NaN      50.0
19  2025-02-01 19:00:00        S2         30.0      42.0
20  2025-02-01 20:00:00        S3         22.0      45.0
21  2025-02-01 21:00:00        S1         22.0      40.0
22  2025-02-01 22:00:00        S2         22.0      45.0
23  2025-02-01 23:00:00        S3          NaN      42.0
24  2025-02-02 00:00:00        S3         22.0      40.0
25  2025-02-02 01:00:00        S1         22.0      50.0
26  2025-02-02 02:00:00        S3         22.0      45.0
27  2025-02-02 03:00:00        S3          NaN      40.0
28  2025-02-02 04:00:00        S2         24.0      50.0
29  2025-02-02 05:00:00        S1          NaN       NaN
30  2025-02-02 06:00:00        S1         22.0      40.0
31  2025-02-02 07:00:00        S2         30.0       NaN
32  2025-02-02 08:00:00        S3         23.0      40.0
33  2025-02-02 09:00:00        S3         24.0      42.0
34  2025-02-02 10:00:00        S1         23.0      40.0
35  2025-02-02 11:00:00        S2         30.0      40.0
36  2025-02-02 12:00:00        S3         23.0       NaN
37  2025-02-02 13:00:00        S1         23.0       NaN
38  2025-02-02 14:00:00        S3          NaN      42.0
39  2025-02-02 15:00:00        S2         30.0      50.0
40  2025-02-02 16:00:00        S1         23.0      50.0
41  2025-02-02 17:00:00        S1          NaN      40.0
42  2025-02-02 18:00:00        S1         22.0      45.0
43  2025-02-02 19:00:00        S2         23.0       NaN
44  2025-02-02 20:00:00        S2         22.0       NaN
45  2025-02-02 21:00:00        S3         30.0      42.0
46  2025-02-02 22:00:00        S1         23.0      40.0
47  2025-02-02 23:00:00        S1         30.0      40.0
48  2025-02-03 00:00:00        S3         22.0      50.0
49  2025-02-03 01:00:00        S2         24.0      40.0


--- AFTER CLEANING ---
             timestamp sensor_id  temperature  humidity  temperature_smoothed  \
0  2025-02-01 00:00:00        S2         24.0      40.0             24.000000
1  2025-02-01 01:00:00        S3         30.0      40.0             27.000000
2  2025-02-01 02:00:00        S1         24.0      50.0             26.000000
3  2025-02-01 03:00:00        S2         24.0      50.0             26.000000
4  2025-02-01 04:00:00        S3         23.0      42.0             23.666667
5  2025-02-01 05:00:00        S3         23.0      40.0             23.333333
6  2025-02-01 06:00:00        S2         24.0      45.0             23.333333
7  2025-02-01 07:00:00        S3         24.0      45.0             23.666667
8  2025-02-01 08:00:00        S1         24.0      45.0             24.000000
9  2025-02-01 09:00:00        S2         22.0      45.0             23.333333
10 2025-02-01 10:00:00        S1         22.0      50.0             22.666667
11 2025-02-01 11:00:00        S2         23.0      50.0             22.333333
12 2025-02-01 12:00:00        S3         23.0      42.0             22.666667
13 2025-02-01 13:00:00        S1         22.0      45.0             22.666667
14 2025-02-01 14:00:00        S1         24.0      42.0             23.000000
15 2025-02-01 15:00:00        S1         23.0      50.0             23.000000
16 2025-02-01 16:00:00        S2         30.0      50.0             25.666667
17 2025-02-01 17:00:00        S2         22.0      50.0             25.000000
18 2025-02-01 18:00:00        S3         22.0      50.0             24.666667
19 2025-02-01 19:00:00        S2         30.0      42.0             24.666667
20 2025-02-01 20:00:00        S3         22.0      45.0             24.666667
21 2025-02-01 21:00:00        S1         22.0      40.0             24.666667
22 2025-02-01 22:00:00        S2         22.0      45.0             22.000000
23 2025-02-01 23:00:00        S3         22.0      42.0             22.000000
24 2025-02-02 00:00:00        S3         22.0      40.0             22.000000
25 2025-02-02 01:00:00        S1         22.0      50.0             22.000000
26 2025-02-02 02:00:00        S3         22.0      45.0             22.000000
27 2025-02-02 03:00:00        S3         22.0      40.0             22.000000
28 2025-02-02 04:00:00        S2         24.0      50.0             22.666667
29 2025-02-02 05:00:00        S1         24.0      50.0             23.333333
30 2025-02-02 06:00:00        S1         22.0      40.0             23.333333
31 2025-02-02 07:00:00        S2         30.0      40.0             25.333333
32 2025-02-02 08:00:00        S3         23.0      40.0             25.000000
33 2025-02-02 09:00:00        S3         24.0      42.0             25.666667
34 2025-02-02 10:00:00        S1         23.0      40.0             23.333333
35 2025-02-02 11:00:00        S2         30.0      40.0             25.666667
36 2025-02-02 12:00:00        S3         23.0      40.0             25.333333
37 2025-02-02 13:00:00        S1         23.0      40.0             25.333333
38 2025-02-02 14:00:00        S3         23.0      42.0             23.000000
39 2025-02-02 15:00:00        S2         30.0      50.0             25.333333
40 2025-02-02 16:00:00        S1         23.0      50.0             25.333333
41 2025-02-02 17:00:00        S1         23.0      40.0             25.333333
42 2025-02-02 18:00:00        S1         22.0      45.0             22.666667
43 2025-02-02 19:00:00        S2         23.0      45.0             22.666667
44 2025-02-02 20:00:00        S2         22.0      45.0             22.333333
45 2025-02-02 21:00:00        S3         30.0      42.0             25.000000
46 2025-02-02 22:00:00        S1         23.0      40.0             25.000000
47 2025-02-02 23:00:00        S1         30.0      40.0             27.666667
48 2025-02-03 00:00:00        S3         22.0      50.0             25.000000
49 2025-02-03 01:00:00        S2         24.0      40.0             25.333333

    humidity_smoothed  temp_norm  hum_norm  sensor_id_encoded
0           40.000000  -0.023106 -1.570705                  1
1           40.000000   2.056464 -1.570705                  2
2           43.333333   1.363274 -0.310107                  0
3           46.666667   1.363274  0.950491                  1
4           47.333333  -0.254170  1.202611                  2
5           44.000000  -0.485233 -0.057988                  2
6           42.333333  -0.485233 -0.688287                  1
7           43.333333  -0.254170 -0.310107                  2
8           45.000000  -0.023106  0.320192                  0
9           45.000000  -0.485233  0.320192                  1
10          46.666667  -0.947360  0.950491                  0
11          48.333333  -1.178423  1.580790                  1
12          47.333333  -0.947360  1.202611                  2
13          45.666667  -0.947360  0.572312                  0
14          43.000000  -0.716296 -0.436167                  0
15          45.666667  -0.716296  0.572312                  0
16          47.333333   1.132211  1.202611                  1
17          50.000000   0.670084  2.211089                  1
18          50.000000   0.439020  2.211089                  2
19          47.333333   0.439020  1.202611                  1
20          45.666667   0.439020  0.572312                  2
21          42.333333   0.439020 -0.688287                  0
22          43.333333  -1.409487 -0.310107                  1
23          42.333333  -1.409487 -0.688287                  2
24          42.333333  -1.409487 -0.688287                  2
25          44.000000  -1.409487 -0.057988                  0
26          45.000000  -1.409487  0.320192                  2
27          45.000000  -1.409487  0.320192                  2
28          45.000000  -0.947360  0.320192                  1
29          46.666667  -0.485233  0.950491                  0
30          46.666667  -0.485233  0.950491                  0
31          43.333333   0.901147 -0.310107                  1
32          40.000000   0.670084 -1.570705                  2
33          40.666667   1.132211 -1.318586                  2
34          40.666667  -0.485233 -1.318586                  0
35          40.666667   1.132211 -1.318586                  1
36          40.000000   0.901147 -1.570705                  2
37          40.000000   0.901147 -1.570705                  0
38          40.666667  -0.716296 -1.318586                  2
39          44.000000   0.901147 -0.057988                  1
40          47.333333   0.901147  1.202611                  0
41          46.666667   0.901147  0.950491                  0
42          45.000000  -0.947360  0.320192                  0
43          43.333333  -0.947360 -0.310107                  1
44          45.000000  -1.178423  0.320192                  1
45          44.000000   0.670084 -0.057988                  2
46          42.333333   0.670084 -0.688287                  0
47          40.666667   2.518591 -1.318586                  0
48          43.333333   0.670084 -0.310107                  2
49          43.333333   0.901147 -0.310107                  1


Task 3 Passed All Tests ✔

In [33]:
from google.colab import files
uploaded = files.upload()

Saving movie_reviews-1.csv to movie_reviews-1.csv

In [34]:
import pandas as pd
df = pd.read_csv(list(uploaded.keys())[0])  # auto detect file name
df.head()

   review_id                review_text  rating
0          1      <p>Amazing movie!</p>     8.0
1          2  Terrible acting & plot!!!     2.0
2          3      <p>Amazing movie!</p>     NaN
3          4  Terrible acting & plot!!!     8.0
4          5      <p>Amazing movie!</p>     5.0

In [35]:
import pandas as pd
import numpy as np
import re
from bs4 import BeautifulSoup
from sklearn.feature_extraction.text import TfidfVectorizer

print("================ TASK 4: MOVIE REVIEWS DATA CLEANING ==================\n")

# =========================================================
# 1️⃣ LOAD DATA
# =========================================================
df = pd.read_csv(list(uploaded.keys())[0])

# =========================================================
# 2️⃣ BEFORE CLEANING (RAW DATA)
# =========================================================
print("--- BEFORE CLEANING ---")
print(df)
print("\n")


# =========================================================
# 3️⃣ CLEANING FUNCTIONS
# =========================================================

def clean_text(text):
    if pd.isna(text):
        return ""
    text = BeautifulSoup(text, "html.parser").get_text()      # Remove HTML tags
    text = text.lower()                                       # lowercase
    text = re.sub(r"[^a-z0-9\s]", "", text)                   # remove punctuation/symbols
    text = re.sub(r"\s+", " ", text).strip()                  # remove extra spaces
    return text


# =========================================================
# 4️⃣ APPLY CLEANING
# =========================================================

cleaned_df = df.copy()

# Clean text column
cleaned_df['clean_text'] = cleaned_df['review_text'].apply(clean_text)

# Fill missing ratings using median
median_rating = cleaned_df['rating'].median()
cleaned_df['rating_filled'] = cleaned_df['rating'].fillna(median_rating)

# Normalize rating (0–10 → 0–1 scale)
cleaned_df['rating_normalized'] = cleaned_df['rating_filled'] / 10

# TF-IDF encoding
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(cleaned_df['clean_text'])

# Convert TF-IDF to DataFrame (top 10 features for display)
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=vectorizer.get_feature_names_out()
)
tfidf_preview = tfidf_df.iloc[:, :10]   # first 10 columns


# =========================================================
# 5️⃣ AFTER CLEANING (FINAL DATASET)
# =========================================================
print("--- AFTER CLEANING ---")
print(cleaned_df[['review_id', 'clean_text', 'rating_normalized']])
print("\n")

print("--- TF-IDF PREVIEW (First 10 features) ---")
print(tfidf_preview)
print("\n")


# =========================================================
# 6️⃣ TEST CASES
# =========================================================

tests_passed = True

# TEST 1 — HTML removed
if "<" not in cleaned_df['clean_text'].iloc[0]:
    pass
else:
    tests_passed = False

# TEST 2 — No missing ratings after filling
if cleaned_df['rating_filled'].isna().sum() == 0:
    pass
else:
    tests_passed = False

# TEST 3 — Normalized ratings are between 0 and 1
if cleaned_df['rating_normalized'].between(0, 1).all():
    pass
else:
    tests_passed = False


# =========================================================
# 7️⃣ FINAL RESULT
# =========================================================

if tests_passed:
    print("Task 4 Passed All Tests ✔")
else:
    print("❌ Some Tests Failed. Fix Required.")

================ TASK 4: MOVIE REVIEWS DATA CLEANING ==================

--- BEFORE CLEANING ---
    review_id                review_text  rating
0           1      <p>Amazing movie!</p>     8.0
1           2  Terrible acting & plot!!!     2.0
2           3      <p>Amazing movie!</p>     NaN
3           4  Terrible acting & plot!!!     8.0
4           5      <p>Amazing movie!</p>     5.0
5           6  Terrible acting & plot!!!     2.0
6           7      <p>Amazing movie!</p>     8.0
7           8  Terrible acting & plot!!!     8.0
8           9      <p>Amazing movie!</p>    10.0
9          10  Terrible acting & plot!!!     5.0
10         11      <p>Amazing movie!</p>     8.0
11         12  Terrible acting & plot!!!     2.0
12         13      <p>Amazing movie!</p>    10.0
13         14  Terrible acting & plot!!!     8.0
14         15      <p>Amazing movie!</p>     NaN


--- AFTER CLEANING ---
    review_id            clean_text  rating_normalized
0           1         amazing movie                0.8
1           2  terrible acting plot                0.2
2           3         amazing movie                0.8
3           4  terrible acting plot                0.8
4           5         amazing movie                0.5
5           6  terrible acting plot                0.2
6           7         amazing movie                0.8
7           8  terrible acting plot                0.8
8           9         amazing movie                1.0
9          10  terrible acting plot                0.5
10         11         amazing movie                0.8
11         12  terrible acting plot                0.2
12         13         amazing movie                1.0
13         14  terrible acting plot                0.8
14         15         amazing movie                0.8


--- TF-IDF PREVIEW (First 10 features) ---
     acting   amazing     movie     plot  terrible
0   0.00000  0.707107  0.707107  0.00000   0.00000
1   0.57735  0.000000  0.000000  0.57735   0.57735
2   0.00000  0.707107  0.707107  0.00000   0.00000
3   0.57735  0.000000  0.000000  0.57735   0.57735
4   0.00000  0.707107  0.707107  0.00000   0.00000
5   0.57735  0.000000  0.000000  0.57735   0.57735
6   0.00000  0.707107  0.707107  0.00000   0.00000
7   0.57735  0.000000  0.000000  0.57735   0.57735
8   0.00000  0.707107  0.707107  0.00000   0.00000
9   0.57735  0.000000  0.000000  0.57735   0.57735
10  0.00000  0.707107  0.707107  0.00000   0.00000
11  0.57735  0.000000  0.000000  0.57735   0.57735
12  0.00000  0.707107  0.707107  0.00000   0.00000
13  0.57735  0.000000  0.000000  0.57735   0.57735
14  0.00000  0.707107  0.707107  0.00000   0.00000


Task 4 Passed All Tests ✔